<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.1.0" />
	<PackageReference Include="Syncfusion.DocumentSDK.AI.AgentTools" Version="*" />
  </ItemGroup>

</Project>
